apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: server
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gcr.io/epresences/server:latest
          ports:
            - containerPort: 4242
          env:
            - name: NODE_ENV
              value: "production"
