apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: server
  name: server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - image: gcr.io/epresences/server:latest
        name: server
        ports:
        - containerPort: 4242
        
