apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: $_SEVER_NAME
  name: $_SEVER_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      run: $_SEVER_NAME
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        run: $_SEVER_NAME
    spec:
      containers:
      - image: gcr.io/epresences/$_SEVER_NAME:latest
        name: $_SEVER_NAME
        ports:
        - containerPort: 4242
        
