apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: main
  name: main
spec:
  replicas: 2
  selector:
    matchLabels:
      run: main
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        run: main
    spec:
      containers:
      - image: gcr.io/epresences/main:latest
        name: main
        ports:
        - containerPort: 4242
        
