apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: maindemo
  name: maindemo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: maindemo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        run: maindemo
    spec:
      containers:
      - image: gcr.io/epresences/maindemo:latest
        name: maindemo
        ports:
        - containerPort: 4242
        
