apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: maindeployment
  name: maindeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: maindeployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        run: maindeployment
    spec:
      containers:
      - image: gcr.io/epresences/$_SEVER_NAME:latest
        name: main
        ports:
        - containerPort: 4242
        
